Repository quackduck/devzat, pull requests merged in 2022-05, with the labels that each got.

#126 add su as an alias for nick
  commands.go
Labels: size/XS

#128 Moved all censor-related functions in a separate file.
  censor.go
  util.go
Labels: size/M

#127 Added Rustrict into the server
  .github/workflows/build.yaml
  .github/workflows/deploy.sh
  .github/workflows/golangci-lint.yaml
  .gitignore
  Admin's Manual.md
  Makefile
  README.md
  censor.go
  go.mod
  rustrict_devzat/.gitignore
  rustrict_devzat/Cargo.lock
  rustrict_devzat/Cargo.toml
  rustrict_devzat/src/lib.rs
Labels: size/L
