Repository quackduck/devzat, pull requests merged in 2023-03, with the labels that each got.

#151 Bold the user names in bridges.
  main.go
Labels: size/XS

#152 Use a new, sleeker id.
  mainserver.yml
Labels: size/XS

#153 Devbot no longer let user bully it.
  commands.go
  util.go
Labels: size/M

#154 Alternate Display for Username in Discord
  Admin's Manual.md
  config.go
  discord.go
  go.mod
  go.sum
  main.go
  slack.go
Labels: size/L
