Repository quackduck/devzat, pull requests merged in 2023-08, with the labels that each got.

#193 Created Devzat status page
  README.md
Labels: size/XS

#196 Fix lstokens command
  rpc.go
Labels: size/XS

#195 Add Magic8Ball Function
  commands.go
Labels: size/S

#197 Center logo in README.MD
  README.md
Labels: size/XS

#200 make myself an admin
  mainserver.yml
Labels: size/XS

#203 Add Ban_Reason to ban function
  commands.go
Labels: size/M

#205 Move the invocation of middleware
  commands.go
  main.go
Labels: size/XS

#207 Add Dialogue to PromptCMD
  commands.go
Labels: size/XS
