Repository quackduck/devzat, pull requests merged in 2023-07, with the labels that each got.

#173 Use the Discord user(/members) nick instead of username
  discord.go
Labels: size/XS

#175 New discord usernames
  discord.go
  go.mod
  go.sum
Labels: size/S

#178 change admin ID
  mainserver.yml
Labels: size/XS

#181 Write twitter errors to logfile instead of in chat
  twitter.go
Labels: size/XS

#184 New admin ids
  mainserver.yml
Labels: size/XS

#187 Add Neofetch CMD (sssh! its a secret :P)
  commands.go
  devzat-data/neofetch.txt
Labels: size/M

#183 devbot improvements
  commands.go
Labels: size/S
